# Manual tuning – Set and get hyperparameters in scikit-learn

## Motivation: module overview
- previously, we kept parameters as default: number of neighbors in KNN; implicit regularization parameter `C` in logistic regression
- hyperparameters are *not* chosen by the model itself; rather by the user. they *control* the training process of the model.
- in this module, we'll show that hyperparameters impact model performance; default is not always the best option
- then, we will show how to set the hyperparameters, and strategies to pick a combination of hyperparameters that maximizes the model's performance

https://scikit-learn.org/stable/auto_examples/linear_model/plot_logistic_path.html#sphx-glr-auto-examples-linear-model-plot-logistic-path-py

**Remember**
- hyperparameters can be specific to each dataset and need to be optimized
- distinguish them from the *estimated* parameters: `model.coef_`

In [15]:
import pandas as pd
adult_census = pd.read_csv("../datasets/adult-census.csv")
target_name = "class"
numerical_columns = ["age", "capital-gain", "capital-loss", "hours-per-week"]

target = adult_census[target_name]
data = adult_census[numerical_columns]

In [16]:
data.head()

   age  capital-gain  capital-loss  hours-per-week
0   25             0             0              40
1   38             0             0              50
2   28             0             0              40
3   44          7688             0              40
4   18             0             0              30

Build a simple predictive model with a scaler and a logistic regression classifier

In [17]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

model = Pipeline(
    steps=[
        ("preprocessor", StandardScaler()),
        ("classifier", LogisticRegression()), # the naming will be important later
    ]
)

In [18]:
# use cross-validation to check how well the model generalizes

In [19]:
from sklearn.model_selection import cross_validate
cv_results = cross_validate(model, data, target)
scores = cv_results["test_score"]

In [20]:
print(
    "Accuracy score via cross-validation:\n"
    f"{scores.mean():.3f} ± {scores.std():.3f}"
)

Accuracy score via cross-validation:
0.800 ± 0.003

Here, the default `C` is 1. To choose a different hyperparameter, we can do this with 
```python
LogisticRegression(C=1e-3)
```

Alternatively, we can use `set_params` method on an existing model

What does the `C` parameter do? It penalizes large parameter values; lower `C` = stronger penalization = less flexible model = higher bias = lower variance
`C` handles L1 regularization (Lasso): sum of absolute value of parameters
L2 = sum of squared values of parameters?

In [22]:
model.set_params(classifier__C=1e-3)
cv_results = cross_validate(model, data, target)
scores = cv_results["test_score"]
print(
    "Accuracy score via cross-validation:\n"
    f"{scores.mean():.3f} ± {scores.std():.3f}"
)

Accuracy score via cross-validation:
0.787 ± 0.002

In [23]:
for parameter in model.get_params():
    print(parameter) # note the double underscore for `classifier__C`

memory
steps
transform_input
verbose
preprocessor
classifier
preprocessor__copy
preprocessor__with_mean
preprocessor__with_std
classifier__C
classifier__class_weight
classifier__dual
classifier__fit_intercept
classifier__intercept_scaling
classifier__l1_ratio
classifier__max_iter
classifier__n_jobs
classifier__penalty
classifier__random_state
classifier__solver
classifier__tol
classifier__verbose
classifier__warm_start

In [24]:
model.get_params()["classifier__C"]

0.001

We can systematically vary the value of `C` to find the optimum

In [28]:
for C in [1e-3, 1e-2, 1e-1, 1, 10]:
    model.set_params(classifier__C=C)
    cv_results = cross_validate(model, data, target)
    scores = cv_results["test_score"]
    print(
        f"Accuracy score via cross-validation with C={C}:\n"
        f"{scores.mean():.3f} ± {scores.std():.3f}"
    )

Accuracy score via cross-validation with C=0.001:
0.787 ± 0.002
Accuracy score via cross-validation with C=0.01:
0.799 ± 0.003
Accuracy score via cross-validation with C=0.1:
0.800 ± 0.003
Accuracy score via cross-validation with C=1:
0.800 ± 0.003
Accuracy score via cross-validation with C=10:
0.800 ± 0.003

Insights
- if `C` is high enough, model performs well
- but this is very amnual -> we'll next see how to do this automatically

# Hyperparameter tuning with grid search

- Now we show how to use grid search to optimize the hyperparamaters for optimal generalization performance of the model

In [29]:
import pandas as pd
adult_census = pd.read_csv("../datasets/adult-census.csv")

In [32]:
target_name = "class"
target = adult_census[target_name]
data = adult_census.drop(columns=[target_name, "education-num"])
data.head()

,age,workclass,education,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,25,Private,11th,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States
1,38,Private,HS-grad,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States
2,28,Local-gov,Assoc-acdm,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States
3,44,Private,Some-college,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States
4,18,?,Some-college,Never-married,?,Own-child,White,Female,0,0,30,United-States

In [33]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(
    data, target, random_state=42
)

In [34]:
# define a pipeline to handle numerical and categorical features

In [35]:
from sklearn.compose import make_column_selector as selector

In [36]:
categorical_columns_selector = selector(dtype_include=object)
categorical_columns = categorical_columns_selector(data)

What we will do
- use a tree-based model as a classifier, specifically, `HistGradientBoostingClassifier`
- this is a histogram-based gradient boosting tree. It is much faster than `GradientBoostingClassifier` for large samples
- 

We don't have time to discuss the details of this model, but
- numerical variables do not need scaling
- categorical variables can be dealt with an `OrdinalEncoder`, even though the coding is not meaningful 
- more specifically, the one-hot encoder requires more tree depth to achieve equivalent splits (why??)

Note that the [docs](https://scikit-learn.org/stable/modules/ensemble.html#histogram-based-gradient-boosting) for hist gradient boosting actually recommends to rely on "native categorical support rather than to treat categorical features as continuous"

We build the `OrdinalEncoder` by passing it the known categories (??)

In [37]:
from sklearn.preprocessing import OrdinalEncoder
categorical_preprocessor = OrdinalEncoder(
    handle_unknown="use_encoded_value", unknown_value=-1
) # this tells to define unkown categories as -1

To build the transformer, we apply the `OrdinalEncoder` for categorical columns, and nothing for the remainder:

In [38]:
from sklearn.compose import make_column_transformer
preprocessor = make_column_transformer(
    (categorical_preprocessor, categorical_columns),
    remainder="passthrough",
)

Now, we build the classifier to predict income categories as before

In [40]:
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.pipeline import Pipeline

model = Pipeline(
    [
        ("preprocessor", preprocessor),
        (
            "classifier",
            HistGradientBoostingClassifier(random_state=42, max_leaf_nodes=4) # will explain the latter in abit
        ),
    ]
)
model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ordinalencoder',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['workclass', 'education',
                                                   'marital-status',
                                                   'occupation', 'relationship',
                                                   'race', 'sex',
                                                   'native-country'])])),
                ('classifier',
                 HistGradientBoostingClassifier(max_leaf_nodes=4,
                                                random_state=42))])

### Tuning using grid search

What's the idea?
- define a set of possible hyperparameter values
- try all combinations, see which one works best
- it's called grid search because we get a 2d (or higher dimensional) grid of hyperparameter combinations

In this context, we focus on hyperparameters
- `learning_rate`: how flexibly the model is updated -> with constant number of trees, a higher learning rate means the model is updated more strongly in each iteration, thus potentially leading to more overfitting.
- `max_leaf_nodes`: controls size of the individual trees -- each tree can have at most as many leaf nodes. More leaf nodes = more flexible = higher variance. 

It's the same algorithm as `GradientBoostingClassifier`, but faster due to some optimizations (inspired by LightGBM)
- better data structure to avoid sorting at each split (histogram datastructure)
- Newton boosting using second-order information about the loss (Hessian)
- Parallelized implementation


Docs
- https://scikit-learn.org/stable/modules/ensemble.html#shrinkage-via-learning-rate
-

In [41]:
from sklearn.model_selection import GridSearchCV

In [43]:
param_grid = {
    "classifier__learning_rate": (0.01, 0.1, 1, 10),
    "classifier__max_leaf_nodes": (3, 10, 30),
}
model_grid_search = GridSearchCV(model, param_grid=param_grid, n_jobs=2, cv=2) # TODO: what is cv?

In [44]:
model_grid_search.fit(data_train, target_train)

GridSearchCV(cv=2,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ordinalencoder',
                                                                         OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                                        unknown_value=-1),
                                                                         ['workclass',
                                                                          'education',
                                                                          'marital-status',
                                                                          'occupation',
                                                                          'relationship',
                                                                          'race',
                                                                          'sex',
                                                                          'native-country'])])),
                                       ('classifier',
                                        HistGradientBoostingClassifier(max_leaf_nodes=4,
                                                                       random_state=42))]),
             n_jobs=2,
             param_grid={'classifier__learning_rate': (0.01, 0.1, 1, 10),
                         'classifier__max_leaf_nodes': (3, 10, 30)})

In [45]:
model_grid_search.best_params_

{'classifier__learning_rate': 0.1, 'classifier__max_leaf_nodes': 30}

- After fitting, we can use it like any other estimators - with the `predict` and `score` methods.
- Internally, it uses the model with the best parameters found during `fit`

In [48]:
model_grid_search.predict(data_test.iloc[:5])

array([' <=50K', ' <=50K', ' >50K', ' <=50K', ' >50K'], dtype=object)

In [50]:
# check the accuracy
accuracy = model_grid_search.score(data_test, target_test)
print(
    f"The test accuracy score of the grid-search pipeline is: {accuracy:.2f}"
)

The test accuracy score of the grid-search pipeline is: 0.88

### The need for a validation set